// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwS5nSVwxc01QtfNJyHmRbFZTvMraBOdk',
    appId: '1:343616734788:web:c5b1bfd9c8cfb2670e1e11',
    messagingSenderId: '343616734788',
    projectId: 'project-management-8994f',
    authDomain: 'project-management-8994f.firebaseapp.com',
    storageBucket: 'project-management-8994f.appspot.com',
    measurementId: 'G-748JZS0EDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIgluvHIJ85a3dgYQDQ5oW28UOyMYP1w',
    appId: '1:343616734788:android:64bb911a21086a5b0e1e11',
    messagingSenderId: '343616734788',
    projectId: 'project-management-8994f',
    storageBucket: 'project-management-8994f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Q0Xt1sLnxVbIQJ6Yzr6LSI6B19coYiw',
    appId: '1:343616734788:ios:62ed41aab7e1fe0c0e1e11',
    messagingSenderId: '343616734788',
    projectId: 'project-management-8994f',
    storageBucket: 'project-management-8994f.appspot.com',
    iosClientId: '343616734788-01vqe6kvd0acva450smc2orud4b4tot1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectSub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Q0Xt1sLnxVbIQJ6Yzr6LSI6B19coYiw',
    appId: '1:343616734788:ios:62ed41aab7e1fe0c0e1e11',
    messagingSenderId: '343616734788',
    projectId: 'project-management-8994f',
    storageBucket: 'project-management-8994f.appspot.com',
    iosClientId: '343616734788-01vqe6kvd0acva450smc2orud4b4tot1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectSub',
  );
}
